### ISSUE TITLE
Add managment and audit tags.

### ISSUE THREAD

**Issue by kgal** [commoncriteria/transforms#18]
Similar to #10, management and audit text are always boilerplate when they are non-null (e.g. “The following actions could be considered for the management functions in FMT: <h:ul>…,” “The following actions should be auditable if FAU_GEN Security Audit Data Generation is included in the PP/ST: <h:ul>…”). It is recommended to define the <management> and <audit> tags such that you can just fill out the associated actions in one or more <action> tags such that the schema automatically populates the boilerplate text and fills out the ul element.

**Comment by robertmclemons** [comment]
This seems to be done. The text appears to be pulled from the XML version of the CC, but I don't understand how. 

Whatever.
