### ISSUE TITLE
Forking or contributing to your repo? And a minor question. 

### ISSUE THREAD

**Issue by nils-tekampe** [commoncriteria/transforms#2]
Hi there,
I was not sure, how to get in contact with you and hope that this issue will get to the right people. 
I love to see what you made here in this repository and we just decided to use the transformation for the biometric cPP (where I'm one of the editors). 
For our cPP we will have to make a few changes to the stylesheets. A few of them are just for editorial reasons (we need app notes where there currently are not app notes foreseen) but the major change is that we are writing three PPs within one document. My plan is to classify the elements in the XML by the use of an attribute and then generate different documents by the use of the stylesheet. As some of the work in these stylesheets seems to go back to the original work that one of my students did years ago, I'm still pretty familiar with the concept and should be able to make the changes. 

My basic question in this context (beside that I just wanted to say "Hi") is whether you would prefer contributions to your repository or want us to fork it and maintain the special kind of transformations that we need separately. I'm not sure whether the changes that we will be making, are of interest for anybody else though. 

My other question in this context: How do you currently handle transformations to PDF or other data formats? Do you simply create the PDF from the HTML manually? 

Thanks
Nils

**Comment by zsmi** [comment]
Hello Nils,

If you need custom stylesheet changes for your cPP you can place the tag below at the bottom of your cPP XML. Within the tag place any stylesheet changes or additions you want and they will be applied when the cPP is build.
  <extra-css>

  </extra-css>

I'm not sure that I follow the app note question. Normally you place the <note> tag where you want an app note to appear. The transform may not allow it to be placed in certain locations but we can probably make changes to the transforms repository if needed.

We currently use 'wkhtmltopdf' to create the pdf files. The command would look similar to: wkhtmltopdf --javascript-delay 15000 <file>.html?expand=on <file>.pdf
Just replace <file> with the name of the HTML file to be converted to pdf. All of our current Protection Profiles are setup to work with Jenkins and build automatically whenever new code is committed. If the biometric cPP is going to be hosted on the commoncriteria Github page then we can set it up this way as well once the project is created.

**Comment by nils-tekampe** [comment]
Hi, 
Thanks for your timely answer. 
Let me go into into some more detail:
1) In many [places](https://github.com/commoncriteria/transforms/blob/c05acbd5f07cd63e968416031d24d6851278fcfb/pp2html.xsl#L725) the current stylesheet seems to assume that only one <appnote> is allowed per assumption/threat/osp. We sometimes have more than one note and would have to change the stylesheet there
2) I'm currently aiming to write all our three PPs that have most of the content in common in one XML file. To achieve this, I introduced a new attribute to the XML file. e.g. I classify an assumption like this:
` <assumption id="A.Fallback" toe-type="BIO PAD INT">`
Within the stylesheet I first introduced a new variable that one can pass on via the commandline as follows:
`<xsl:param name="target" select="'BIO'"/>`
And then, I'm planning to qualify all the places, where content is added to the HTML as follows:
`xsl:for-each select="cc:assumption[contains(@toe-type, $target) or not(@toe-type)]">
        <dt>`

The stylesheet will still work without the toe-type attribute but these changes will allow us to maintain our three documents within one XML file which will make our lives much easier. 

If this would be OK for you, I will apply the necessary changes to a fork and submit a pull request. 

BTW: Our repo is currently a private repo. This has been decided by the whole team. But if you are interested, I can grant you access. 

Regards
Nils 

P.S. Thanks for the tipp on wkhtmltopdf. I'll give it a try.

**Comment by zsmi** [comment]
Nils,

Your changes sound fine to me. From your description it doesn't look like it will break any of our current protection profiles and so your idea of creating a fork and submitting a pull request seem reasonable. We look forward to your contribution.

I don't need access to the repository. I will leave that work to your team.

Thank you.
