### ISSUE TITLE
No spaces for cPP

### ISSUE THREAD

**Issue by kgal** [commoncriteria/transforms#21]
Not sure if there’s a way to do this in the schema but typically the “NDcPP” is referenced with no space, unlike for example the App PP, GPOS PP, MDF PP, etc. The same is true for other collaborative PPs. If possible, the makefile should delete whitespace immediately following the short name of a Base-PP if and only if the short parameter ends with lowercase c (e.g. NDc PP becomes NDcPP but GPOS PP remains untouched).

**Comment by robertmclemons** [comment]
This should be fixed, at least for Base PPs in Modules.

**Comment by robertmclemons** [comment]
Yeah. Whatever. Closing it until someone complains.
