### ISSUE TITLE
Table titles listed before the table

### ISSUE THREAD

**Issue by lewyble** [commoncriteria/transforms#34]
Received comment from DISA for MDF to have the table number/title listed before the table.

**Comment by kgal** [comment]
As far as I know, the for the tables generated by transforms, the number and title is placed before the table. I see that the MDF is manually putting table number/titles after the table body:
https://github.com/commoncriteria/mobile-device/blob/5e5e1317e20e05b5979ac94d046ab32cca5d20bd/input/mobile-device.xml#L992)

The preferred way to put in table captions is
```
<table xmlns="http://www.w3.org/1999/xhtml">
  <caption> Table <cc:ctr ctr-type="Table" id="something">: A Great Title </cc:ctr></caption>
  <tr><th>Column Name 1</th><th>Column Name 2</th>...</tr>
  <tr><td>Data ...
  ...
</table>
```

**Comment by robertmclemons** [comment]
They are all before the table now unless the author goes out of his way to screw it up. The Wiki says to put them before.
