### ISSUE TITLE
"Consistency of Requirements" default text

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#47]
Two issues identified in the default intro text for the "Consistency of Requirements" section of the consistency rationale:
1. The first sentence is pluralizing either the "name" or "target-product" attribute of the Module where it should be singular,
e.g. "This PP-Module identifies several SFRs from the NDcPP that are needed to support Authentication Servers functionality" - should be "Authentication Server" instead.

(Note that there is a second instance of this later in the paragraph but that sentence is written in such a way that the pluralization is fine)

2. The second to last sentence is missing a period after it, e.g. "The PP-Module also identifies a number of modified SFRs from the NDcPP that are used entirely to provide functionality for Authentication Servers The rationale for why this does not conflict with the claims defined by the NDcPP are as follows:"

**Comment by kgal** [comment]
These should be fixed (https://github.com/commoncriteria/transforms/commit/b88e4e7d11153d4004b690a45f16a54960d51b63)

**Comment by jfisherbah** [comment]
confirmed
