### ISSUE TITLE
<ext-comp-class> text location

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#48]
The text for <ext-comp-class> should be going in the ECD under the heading for that particular class. When this text is present, it should be replacing what the template inserts by default. 

See for example the SBC module - the <ext-comp-class> text is currently under section 5.2.4 in the main body of the document. It should be located under the class header in the ECD for the FFW class instead (section C.2.2 in SBC). The text currently in section C.2.2 is not appropriate for an extended class because it incorrectly states the class is defined in CC Part 2.

**Comment by kgal** [comment]
I think you're looking for the "class-description" tag that is subordinate to a section tag. Look at https://github.com/commoncriteria/vpnclient/blob/master/input/vpnclient.xml#L4339 . That being said, I'm not sure what the ECD description tag is supposed to do.

**Comment by jfisherbah** [comment]
The class-description tag works for this. I would have expected that class-description would populate under the relevant header in the main body and the ext-comp-class would populate under the corresponding ECD heading for that class. It looks like the functionality of these two things are reversed.

There is no functional issue since the capability exists to do both things, it's just counterintuitive which tag is used for which purpose, so the issue can be closed.


For background (to address the last sentence) - 

The ECD description is needed so that we have a capability to specify our own text in the ECD for when a class is defined that is not in CC Part 2 (e.g. it's not FAU, FCS, FDP, etc.). This is needed for the following requirement:

"APE_ECD.1-7 The evaluator shall examine the extended components definition to determine that each definition of a new functional class uses the existing CC functional classes as a model for presentation."

The boilerplate text that is used by default in the ECD assumes that it's underneath a class that already exists in part 2, so it's important for us to have the ability to replace that in the rare instance when brand new classes are defined (e.g. FFW, FPF).

**Comment by robertmclemons** [comment]
Looks like this one can be closed.
