### ISSUE TITLE
SFR type naming consistency

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#49]
The table in the "Consistency of Requirements" section of the consistency rationale (6.x.4) should ideally use the same terminology and ordering as the non-mandatory SFR appendices for the sake of consistency. Currently the non-mandatory sections in the table go:

Optional -> Selection-based -> Objective -> Implementation-based

For naming and ordering consistency this should instead be:

Strictly Optional -> Objective -> Implementation-dependent -> Selection-based

**Comment by jfisherbah** [comment]
The ordering has been corrected but the table heading still says "implementation-based" while A.3 is "implementation-dependent" - the table heading should be changed for consistency.

**Comment by kgal** [comment]
They all should be 'implementation-based' now (I thought that that would be more similar to 'selection-based' as opposed to 'implementation-dependent' ).

**Comment by jfisherbah** [comment]
I don't have an issue with that but you may want to confirm with NIAP since we've been using "implementation-dependent" for a while and documents have been written with that in mind. If this is changed there will be some author-inserted text in the XML that will need to be updated in each PP/module for consistency when the transforms are updated.

**Comment by robertmclemons** [comment]
Everything has been changed to "Implementation-dependent" now. Ideally it could be changed to "Conditional," but whatevs.
