### ISSUE TITLE
>3 SFRs dependent on selection

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#51]
Is it possible for a sel-based SFR to depend on arbitrarily many SFRs or is the limit three (using the "on-sel", "and", and "also" attributes? 

FTP_ITC.1/H323 in the SBC Module depends on selections made in four different SFRs but it's unclear whether the current transforms supports this or if there is a hard cap at three.

**Comment by kgal** [comment]
As many as you want: https://github.com/commoncriteria/pp-template/wiki/Just-Depends

**Comment by jfisherbah** [comment]
confirmed
