### ISSUE TITLE
ECD schema validation failure for packages

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#64]
Functional packages (e.g. tls, ssh) need to have extended component definitions (ECDs) but the schema for a package that uses the ECD related tags throws validation errors for all of those tags. 

The build process still handles them correctly and the ECD builds without error, so the schema validation failures are false.

This is a low impact issue since it doesn't actually prevent the desired functionality from working, but the validation errors are a potential source of confusion especially if future updates have legitimate errors that are difficult to diagnose because of the false ones.

**Comment by robertmclemons** [comment]
This should be fixed.
