### ISSUE TITLE
suppression of CC acronyms

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#66]
the use of the <suppress> tag in the tech-terms section is unable to suppress CC-related acronyms (e.g. to forcibly omit 'TSFI' from the acronyms list). Ideally this functionality should be incorporated since acronyms should not be referenced in a document unless they are used at least once in the body of the document, so we should have the ability to tailor the predefined acronyms list to remove unused ones.

**Comment by robertmclemons** [comment]
Try using the name of the item rather than the acronym. e.g.:
```<suppress>TSF Interface</suppress>```
as the first thing in the ```<tech-terms>``` section.

**Comment by jfisherbah** [comment]
confirmed
