### ISSUE TITLE
update to boilerplate text for refinement operation

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#70]
In PPs and PP-Modules, the default text bullet for refinement states the following:

  "Refinement operation (denoted by bold text or strikethrough text): Is used to add details to a requirement (including replacing an assignment with a more restrictive selection) or to remove part of the requirement that is made irrelevant through the completion of another operation, and thus further restricts a requirement."

The parenthetical can be removed as the act of replacing an assignment with a selection is now considered to be (partially) completing the assignment rather than refining it. The use of bold text in that specific situation just created unnecessary confusion for the reader.

**Comment by robertmclemons** [comment]
Done
