### ISSUE TITLE
CC Part 1 reference in Implicitly Satisfied Requirements boilerplate

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#71]
The boilerplate text in the "Implicitly Satisfied Requirements" appendix in PP-Modules includes the following line:

"This approach is permitted by [CC] Part 1, 8.2 Dependencies between components."

This is true for CC v3.1r5, but in CC:2022, this section is now 8.3. Some mechanism is needed to flag a Module as conformant to CC:2022 so that the boilerplate text in this case can be accurate with respect to the claimed CC edition.

**Comment by robertmclemons** [comment]
I've added a using-cc2022 element to the schema in the pp-preferences element. So far it's not hooked up to anything, but it's there to be used for such things.

**Comment by robertmclemons** [comment]
Until this is fixed, you should be able to add the boilerplate="no" attribute to the appendix element and then just full out  the section manually, e.g.:

<appendix title="Implicitly Satisfied Requirements" id="satisfiedreqs" boilerplate="no">

**Comment by robertmclemons** [comment]
Fixed. Should be merged into transforms by COB today.
