### ISSUE TITLE
ECD in Packages

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#76]
Packages currently support the family level <ext-comp-def> tags but not the component level tags for <comp-lev>, <management>, <audit>, and <dependencies>. Technically functional packages have no CC workunits so this is not needed within the context of the package itself, but since PPs and Modules that reference the package must have fully complete ECDs it is preferable for the package to include this so that the PP author does not need to redefine this in each PP or Module that conforms to the pakcage.

**Comment by robertmclemons** [comment]
This appears to be fixed.  Can it be closed?

**Comment by jfisherbah** [comment]
yes

**Comment by jfisherbah** [comment]
closing
