### ISSUE TITLE
Inherited SOs

### ISSUE THREAD

**Issue by kgal** [commoncriteria/transforms#8]
The current schema doesn’t permit a Module not to have TOE Objectives. This is needed both because the <SOs> section can’t be blank but also because each threat must have at least one <objective-refer>. Placeholders were inserted so the page would build, but this causes sections 4.1 and 4.3 and the consistency rationale to have placeholder text that shouldn’t be there in the final version.
Please provide guidance on whether:
a. TOE objectives should be defined and mapped to fit with the schema
b. We should leave the placeholder text as-is and wait for schema updates that allow there to be a Module that does not define TOE objectives

**Comment by kgal** [comment]
You can now associate an SO as having been inherited from a base
by including a 'base' tag instead of a 'description' tag.

**Comment by dmhale1** [comment]
For PP-Modules and TOE objectives, right now PP-Modules must have objectives for the TOE.  They need to account for objectives in their base if their SPD impacts it as well.  In an updated version of the CC, PP-Modules are no longer required to, but may still have objectives for the TOE.  If there are objectives, then (as is the case currently) if the PP-Module's SPD impacts an objective in its base, then it will still have to be accounted for.

**Comment by kgal** [comment]
If you just reference the objective in the base it looks like this (assuming it's called O.PLACEHOLDER):
![NoNewObjectives](https://user-images.githubusercontent.com/7069905/71533642-fc04d700-28c7-11ea-875b-576a9cc770b9.png)

Is this what NIAP wants?

**Comment by dmhale1** [comment]
This looks good for now as we have to have objectives for PP-Modules. However, later on when we are allowed to just reference objectives in the base and are not mandated to add new ones, we may not need the Table in 4.3. We may just have text there as well that states it is not needed because we don't have any objectives.
