### ISSUE TITLE
PP-Modules duplicating Additional SFRs

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#80]
In a PP-Module, SFR components under the <additional-sfrs> tag of <base-pp> are being duplicated (it may be happening elsewhere but this is the only situation it has been observed so far)

See for example section 5.1.2 of https://commoncriteria.github.io/mdm-agent/master/mdm-agent.html - all three Additional SFRs are duplicated

**Comment by robertmclemons** [comment]
I'm not seeing this. It could be that I already accidently fixed it. Try updating transforms.

**Comment by jfisherbah** [comment]
Issue still persists, see for example 5.1.2.2 of https://commoncriteria.github.io/mdm-agent/master/mdm-agent.html - there are two copies of FCS_STG_EXT.4 present.

**Comment by robertmclemons** [comment]
Huh. I see it now. Weird that it duplicates in additional SFRs section, but not in ECD. Meanwhile I found another problem with repeats in the ECD.

**Comment by robertmclemons** [comment]
Updating transforms seems to have fixed it. Not sure why, but I have been poking around in that area.

**Comment by jfisherbah** [comment]
I don't see where it's fixed. I'm looking at https://commoncriteria.github.io/mdm-agent/master/mdm-agent.html and github shows the latest transforms are pulled and I still see duplicates in section 5.1.2.2 among other places

**Comment by robertmclemons** [comment]
Yeah. Something weird might be going on, but it looks okay now.
[https://commoncriteria.github.io/mdm-agent/master/mdm-agent-release.html](https://commoncriteria.github.io/mdm-agent/master/mdm-agent-release.html)

**Comment by jfisherbah** [comment]
I see it's working in the linked version but it's not working in https://commoncriteria.github.io/mdm-agent/master/mdm-agent.html. The "-release" HTML doesn't have the evaluation activities embedded in it (which NIAP wants to have added since they're moving away from SDs), so I have generally used the one I have linked because it has the EAs.

**Comment by robertmclemons** [comment]
So, is NIAP going to publish mdm-agent as a single document? Without an SD?

**Comment by jfisherbah** [comment]
My understanding is that future PPs/Modules/Packages will be published as single standalone documents rather than pushing EAs off into an SD, similar to how MDF/MDM/App PP have historically been done. I believe since it wasn't technically something that went into those docs in CC v3.1 they wanted to have it separate, but the new CC:2022 Part 4 talks about evaluation activities and methods so the standard was updated to accommodate the original way they wanted them to be handled.

**Comment by robertmclemons** [comment]
Okay, well I'd love to get rid of the SD. That would simplify things, but it would take some disentangling. 

Try pulling the transforms and try again. I think I've fixed it for all the versions.

**Comment by jfisherbah** [comment]
confirmed fixed
