### ISSUE TITLE
Automatic table numbering

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#81]
The acronyms table in a PP/Module/Package should be automatically captioned and numbered the same way as other automatic tables are (see e.g. auditable events and SAR tables).

Additionally, unsure if this capability already exists but there should be a way (if feasible) to add an arbitrary table caption tag to a user-generated HTML table for consistency. For example, the Implicitly Satisfied Requirements table (typically appendix D, see for example https://commoncriteria.github.io/mdm-agent/master/mdm-agent.html) is user-generated in HTML but doesn't have a caption, so it's visually inconsistent with other tables in the same document.

**Comment by jfisherbah** [comment]
update - arbitrary user generated tables can be captioned using html div tag. Recommendation to apply automatic caption to acronyms table still applies

**Comment by jfisherbah** [comment]
update 2 - there are actually many tables that exist in the document that do not get captioned automatically (e.g. everything in the consistency rationale), Ideally we should probably handle all of them consistently

**Comment by robertmclemons** [comment]
Added captions and numbers to the tables in the Consistency Rationale section of Modules

**Comment by robertmclemons** [comment]
For user generated tables it's probably better to use the html ```<caption>``` element. E.g. The module-reform branch of vpnclient does this for the Implicitly Satisfied Requirements:
```<h:table>
	<h:caption>
		<h:b><ctr ctr-type="Table" pre="Table " id="imp-sat-reqs-table">: Implicitly Satisfied Requirements</ctr></h:b>
      </h:caption>```

**Comment by robertmclemons** [comment]
Added caption and number to acronyms table

**Comment by jfisherbah** [comment]
should probably add for bibliography too

**Comment by robertmclemons** [comment]
Done.

**Comment by robertmclemons** [comment]
closing
