### ISSUE TITLE
<base-pp> tag pulling incorrect PP information

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#83]
The <base-pp> tag in a PP-Module appears to be using a CC github reference to identify the Base-PP that the associated Module section is referencing. The current MDM Agent module (https://commoncriteria.github.io/mdm-agent/master/mdm-agent.html) currently references the MDF PP as a Base-PP (see line 580 of mdm-agent.xml) but all dynamic references to the Base-PP in the actual Module say "MDM Agent PP" or "Protection Profile for MDM Agent" rather than "MDF PP" or "Protection Profile for Mobile Device Fundamentals". See sections 5.1 and 6.1 of the linked module for reference.

Section 6.2 also erroneously says "Protection Profile for MDM Agent" rather than "Protection Profile for Mobile Device Management" but the various references to "MDM PP" are correct as-is.

Issue has only been observed in mdm-agent so it's unclear whether this is an issue with the MDM Agent Module, the individual Base-PPs that it's referencing, or the transforms/build process as a whole.

**Comment by robertmclemons** [comment]
I have seen this problem elsewhere. It is quite confounding. 
The current Barney Rubble solution is to manually specify the name, e.g.: 

    
    <base-pp id="bpp-gpos" name="General-Purpose Operating Systems" short="GP"> 
      <git>
	<url>https://github.com/commoncriteria/operatingsystem</url>
	<branch>release-4.3</branch>
      </git>
	<url>https://www.niap-ccevs.org/Profile/Info.cfm?PPID=469&amp;id=469</url>

**Comment by jfisherbah** [comment]
This works - the only (minor) suggestion I would have is for the "XYZ PP Security Functional Requirements Direction" sections to use the `name` attribute rather than the `short` attribute in the section title. Not really a big deal that it uses `short` though.

**Comment by robertmclemons** [comment]
Changes to use the expanded PP Name

**Comment by jfisherbah** [comment]
confirmed resolved
