### ISSUE TITLE
"Use Case Templates" appendix no longer working

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#85]
The current draft of mdm-agent needs an appendix called "Use Case Templates" that define the SFR claims that must be made when the TOE embodies a given use case. This was present in the most recent published MDM Agent Module (https://www.niap-ccevs.org/MMO/PP/mod_mdm_agent_v1.0.pdf) as Appendix E. 

In the current transforms, this is no longer valid XML because it doesn't recognize the <usecase> tag as valid in this setting. There needs to be something to attach an id value to down here so that the Use Cases section in the introduction can have an appropriate xref to it.

**Comment by robertmclemons** [comment]
All the use-case stuff is specified in the Introduction now.  
See, https://github.com/commoncriteria/pp-template/wiki/Use-Cases-Section
So in this case, you need to assign id attributes to the three selections referenced in the use cases and then add a <config> element to the two use cases that require selections. The use-cases section of gpcp is a good example. If there is at least one <config> element, then it should auto-generate an appendix.

**Comment by jfisherbah** [comment]
updated XML for MDM Agent and the stub text populated in the use case sections but no appendix was generated. Not clear if it's a module vs PP issue or if it's because the only triggers in this module are "make this SFR selection" rather than "include this SFR claim" (i used the selection IDs in the ref-id tag so in theory it should have worked but the example for doing that is only in the wiki and not in the actual GPCP PP)

**Comment by robertmclemons** [comment]
It turns out that for Modules you have to insert an empty appendix:
  ```<appendix title="Use Case Templates" id="blah"/>``` 
I've done that for mdm-agent and it seems to work.
And I fixed the Wiki.

**Comment by jfisherbah** [comment]
confirmed fixed

**Comment by robertmclemons** [comment]
closing
