### ISSUE TITLE
formatting of PP reference when threat inherited from Base-PP

### ISSUE THREAD

**Issue by jfisherbah** [commoncriteria/transforms#88]
In PP-Modules we currently have the ability to bring a threat in from a Base-PP for the purpose of mapping it to an objective in the Module. See for example section 4.3 of (https://commoncriteria.github.io/email-client/master/email-client.html). However, there appears to be no way to put a space in the referenced PP name. 

The actual code uses a tag <from base=""> where 'base' must be the same as the 'id' parameter of a <base-pp>. However, it then just puts the actual id value as-is in brackets. Since the id value can't contain spaces, this creates inaccurate references. So for example, instead of saying "from [App PP]" which is the desired behavior, it must say "from [AppPP]" because there's no way to override the 'id' value (that can't contain a space).

More a nuisance cosmetic issue than an actual problem but worth flagging.

**Comment by robertmclemons** [comment]
I think this is fixed. Now it produces "App PP" rather than "AppPP."

**Comment by jfisherbah** [comment]
confirmed fixed
