### ISSUE TITLE
Iterated SFRs in consistency rationale.

### ISSUE THREAD

**Issue by kgal** [commoncriteria/transforms#9]
Iterated SFRs are not interacting correctly with the consistency rationale. The VPN Client Module has an iterated SFR, FMT_SMF.1/VPN. By default, it is showing up in the table as FMT_SMF.1. 
Entering a con-mod tag with id of “fmt_smf.1/VPN” does not work, as the blank FMT_SMF.1 remains there. 
Entering a con-mod tag with id of “fmt_smf.1” populates the blank entry, but then the SFR does not have its proper iteration name.
This has to be something that is done on the base-pp level and not the f-component level since the Module can have multiple base-pps (as VPN Client does).
a. Note that WLAN AS also has the same issue because there are SFRs named FCS_CKM.1/WPA, FCS_CKM.2/GTK, FCS_CKM.2/PMK, and FCS_CKM.2/DISTRIB, none of which display correctly in the consistency rationale.  
As a side effect (possibly because there are multiple iterations of the same component and the makefile can’t figure out which one to use), using the base-pp <con-mod> tag doesn’t display anything at all, while using the <consistency-rationale> tag underneath <f-component> displays the proper text so only the SFR title is wrong.

**Comment by kgal** [comment]
Is this with the current VPN Client that's in github? I just built it using the most recent transforms and it seems fine.

**Comment by dmhale1** [comment]
I agree that appears to be correct in the current draft deployed version.
